- .gitignore
- docs/development_guides/setup_env.md
- docs/get_started/installation.md
- versioned_docs/version-0.9.1/development_guides/setup_env.md
- versioned_docs/version-0.9.1/installation/installation.md
- versioned_docs/version-1.0.0/development_guides/setup_env.md
- versioned_docs/version-1.0.0/installation/installation.md
- versioned_docs/version-1.0.1/development_guides/setup_env.md
- versioned_docs/version-1.0.1/get_started/installation.md
> docs: update install guide

- sidebars.js
> add chaos daemon in the sidebar

- docs/development_guides/add_chaos_daemon.md
- versioned_docs/version-1.0.1/development_guides/add_chaos_daemon.md
fix format, before this pr:
after format:
> docs: fix format for development document

- docs/development_guides/develop.md
- docs/development_guides/setup_env.md
- versioned_docs/version-0.9.1/development_guides/develop.md
- versioned_docs/version-0.9.1/development_guides/setup_env.md
- versioned_docs/version-1.0.2/development_guides/develop.md
- versioned_docs/version-1.0.2/development_guides/setup_env.md
> chore: supplement how to dev dashboard

- docs/development_guides/add_chaos_daemon.md
- docs/development_guides/dev_hello_world.md
- versioned_docs/version-1.0.2/development_guides/add_chaos_daemon.md
- versioned_docs/version-1.0.2/development_guides/dev_hello_world.md
1. some code is changed in Chaos Mesh, need to update in the document
2. some minor fix, for example, change the absolute path to relative path, need to load images to kind
> docs: some fix on development document

- docs/chaos_experiments/dns_chaos.md
- sidebars.js
add document for dns chaos, should be merged after https://github.com/chaos-mesh/chaos-mesh/pull/1039
> docs: add document for dns chaos

- versioned_docs/version-1.0.2/chaos_experiments/io_chaos.md
> Fix a wrong note format

- docs/get_started/get_started_on_kind.md
- docs/get_started/get_started_on_minikube.md
- docs/user_guides/installation.md
- versioned_docs/version-0.9.1/installation/get_started_on_kind.md
- versioned_docs/version-0.9.1/installation/get_started_on_minikube.md
- versioned_docs/version-0.9.1/installation/installation.md
- versioned_docs/version-1.0.2/get_started/get_started_on_kind.md
- versioned_docs/version-1.0.2/get_started/get_started_on_minikube.md
- versioned_docs/version-1.0.2/user_guides/installation.md
> doc: add note for use install.sh

- src/components/Banner.jsx
- src/pages/index.js
- src/styles/custom.css
> chore: add community survey banner

- docs/chaos_experiments/network_chaos.md
- versioned_docs/version-1.0.3/chaos_experiments/network_chaos.md
- versioned_docs/version-1.1.1/chaos_experiments/network_chaos.md
> Add external targets document

- docs/development_guides/add_chaos_daemon.md
- versioned_docs/version-1.0.3/development_guides/add_chaos_daemon.md
- versioned_docs/version-1.1.1/development_guides/add_chaos_daemon.md
Resolve https://github.com/chaos-mesh/chaos-mesh/issues/1326.
> fix: update add_chaos_daemon code to the latest

- blog/2021-01-08-how-to-simulate-io-faults-at-runtime.md
The 'make' should be the third-person singular form.
Signed-off-by: Xu Wang <cngesaint@gmail.com>
> Fix a grammatical error

- blog/2020-11-26-how-a-top-game-company-uses-chaos-engineering-to-improve-testing.md
- blog/2021-01-08-how-to-simulate-io-faults-at-runtime.md
Signed-off-by: Mila Wu <wuzaixuan@pingcap.com>
> delete: overlapping paragraph and fix summary

- blog/2020-01-15-chaos-mesh-your-chaos-engineering-solution.md
- blog/2020-03-18-run-your-first-chaos-experiment.md
- blog/2020-07-28-chaos-mesh-join-cncf-sandbox-project.md
- blog/2020-08-14-building_automated_testing_framework.md
- blog/2020-10-14-chaos-mesh-x-hacktoberfest.md
- blog/2020-10-30-chaos-engineering-breaking-things-intentionally.md
- blog/2020-11-26-how-a-top-game-company-uses-chaos-engineering-to-improve-testing.md
- blog/2020-9-18-chaos-mesh-action-integrate-chaos-engineering-into-your-ci.md
- blog/2021-01-08-how-to-simulate-io-faults-at-runtime.md
- blog/2021-02-05-celebrating-one-year-of-chaos-mesh-looking-back-and-ahead.md
- docs/faqs.md
- docusaurus.config.js
- versioned_docs/version-0.9.1/faqs.md
- versioned_docs/version-1.0.3/faqs.md
- versioned_docs/version-1.1.1/faqs.md
Signed-off-by: Mila Wu <wuzaixuan@pingcap.com>
> update slack links to join the Chaos Mesh workspace

- docs/user_guides/offline_installation.md
- sidebars.js
> add document for offline installation

- README.md
- blog/2021-02-05-celebrating-one-year-of-chaos-mesh-looking-back-and-ahead.md
- docs/chaos_experiments/network_chaos.md
- docs/development_guides/dev_hello_world.md
- docs/development_guides/setup_env.md
- docs/user_guides/installation.md
- docs/user_guides/run_chaos_experiment.md
After a review of the doco to learn more about the project, just throwing in fixes for a few small typos, code fences, removing some extraneous whitespace, etc, but no actual content change.
> Editorial review: typos, spacing, code fencing

- docs/user_guides/run_chaos_experiment.md
Using sh to install the script is not working ,see the following output:
> Update install command

- docs/user_guides/offline_installation.md
> offline install doc: add image of coredns && some minor update

- docs/chaos_experiments/aws_chaos.md
- sidebars.js
Signed-off-by: “fewdan” <fewdan@hotmail.com>
> add aws docs

- docs/chaos_experiments/dns_chaos.md
incorrect helm repo being specified.   needs to be "chaos-mesh/chaos-mesh"
> repo from "helm/chaos-mesh" to "chaos-mesh/chaos-mesh"

- docs/user_guides/dashboard.md
- docs/user_guides/installation.md
> update document about chaos dashboard

- docs/overview/features.md
Signed-off-by: Ran <huangran@pingcap.com>
Missing linebreaks.
> docs: fix wrong format in features.md

- docs/chaosd-overview.md
Signed-off-by: Joyinqin <joyinqin@pku.edu.cn>
This pr is translated from: https://github.com/chaos-mesh/website-zh/pull/10
> docs: add chaosd overview

- docs/offline-installation.md
Signed-off-by: Joyinqin <joyinqin@pku.edu.cn>
This pr is translated from: https://github.com/chaos-mesh/website-zh/pull/15
> docs: add offline-installation.md

- docs/common/quick-run.md
- docs/common/verify-installation.md
- docs/production-installation-using-helm.md
- docs/quick-start.md
- sidebars.js
Signed-off-by: Joyinqin <joyinqin@pku.edu.cn>
This pr is translated from: https://github.com/chaos-mesh/website-zh/pull/15
docs: add production-installation-using-helm.md
> docs: add helm-installation 

- docs/user_guides/installation.md
- add notes for PKS k8s cluster installations.
> add notes for PKS k8s cluster installations

- docs/chaosd-overview.md
- docs/simulate-host-console-in-physical-nodes.md
- sidebars.js
Signed-off-by: TomShawn <41534398+TomShawn@users.noreply.github.com>
This PR:
+ translates `simulate-host-console-in-physical-nodes.md` from https://github.com/chaos-mesh/website-zh/pull/26 and https://github.com/chaos-mesh/website-zh/pull/55
+ updates `chaosd-overview.md` from https://github.com/chaos-mesh/website-zh/pull/40.
> add Simulate Host Faults and update chaosd overview

- docs/inspect-chaos-mesh-workflow.md
Signed-off-by: Charlotte Liu <37295236+CharLotteiu@users.noreply.github.com>
Add inspect Chaos Mesh workflow doc.
> docs: add inspect chaos mesh workflow doc

- docs/create-chaos-mesh-workflow.md
- docs/simulate-kernel-chaos-on-kubernetes.md
Signed-off-by: TomShawn <41534398+TomShawn@users.noreply.github.com>
This PR adds create-chaos-mesh-workflow.md and simulate-kernel-chaos-on-kubernetes.md.
Translated from https://github.com/chaos-mesh/website-zh/pull/22 and https://github.com/chaos-mesh/website-zh/pull/36.
> Add 2 docs

- docs/simulate-jvm-application-chaos.md
Signed-off-by: Liuxiaozhen12 <82579298+Liuxiaozhen12@users.noreply.github.com>
This PR is translated from https://github.com/chaos-mesh/website-zh/pull/32.
> dcos: add simulate JVM application faults.md

- docs/simulate-process-chaos-in-physical-nodes.md
Signed-off-by: en-jin19 <jinenwei@pingcap.com>
In this PR, I have added a document about simulating process faults
This PR is translated from: chaos-mesh/website-zh#52
> docs: add a domument for simulate process faults

- docs/simulate-disk-pressure-in-physical-nodes.md
Signed-off-by: Liuxiaozhen12 <82579298+Liuxiaozhen12@users.noreply.github.com>
This PR is translated from https://github.com/chaos-mesh/website-zh/pull/16 and https://github.com/chaos-mesh/website-zh/pull/43.
> docs: add simulate disk faults.md

- docs/simulate-heavy-stress-in-physical-nodes.md
Signed-off-by: en-jin19 <jinenwei@pingcap.com>
In this PR, I have added a document about stress simulation
This PR is translated from: https://github.com/chaos-mesh/website-zh/pull/52
> Docs: add a document for stress simulation

- docs/simulate-pod-chaos-on-kubernetes.md
Signed-off-by: Xiaozhen Liu <liuxiaozhen@pingcap.com>
This PR is translated from https://github.com/chaos-mesh/website-zh/pull/13 and https://github.com/chaos-mesh/website-zh/pull/43/files.
> docs: add simulate-pod-chaos-on-kubernetes.md

- docs/run-chaos-experiments-in-serial-or-parallel.md
Signed-off-by: Xiaozhen Liu <liuxiaozhen@pingcap.com>
This PR is translated from https://github.com/chaos-mesh/website-zh/pull/20.
> docs: add run-chaos-experiments-in-serial-or-parallel.md

- docs/upgrade-to-2.0.md
Signed-off-by: Liuxiaozhen12 <82579298+Liuxiaozhen12@users.noreply.github.com>
This PR is translated from https://github.com/chaos-mesh/website-zh/pull/62 and https://github.com/chaos-mesh/website-zh/pull/37.
> docs: add upgrade to Chaos Mesh 2.0

- docs/configure-development-environment.md
Signed-off-by: Xiaozhen Liu <liuxiaozhen@pingcap.com>
This PR is translated from https://github.com/chaos-mesh/website-zh/pull/39 and https://github.com/chaos-mesh/website-zh/pull/65.
> dcos: add: Configure the Development Environment.md

- blog/2020-08-14-building_automated_testing_framework.md
removed an accidental word and fixed the wrong channel name:)
Signed-off-by: Mila Wu <wuzaixuan@pingcap.com>
> blog: update-argo-article

- docs/chaosctl-tool.md
Signed-off-by: Yajing Wang <yajing.wang@pingcap.com>
This PR aligned with: https://github.com/chaos-mesh/website-zh/pull/5
> docs: add chaosctl

- docs/simulate-http-chaos-on-kubernetes.md
Signed-off-by: hexilee <i@hexilee.me>
> add an annotation about client/HTTPS supports for docs of HTTPChaos

- docs/simulate-process-chaos-in-physical-nodes.md
fix command in doc 'simulate process chaos in physical node'
> docs: fix command in doc 'simulate process chaos in physical node'

- docs/run-a-chaos-experiment.md
- docs/simulate-network-chaos-on-kubernetes.md
- versioned_docs/version-2.0.1/run-a-chaos-experiment.md
- versioned_docs/version-2.0.1/simulate-network-chaos-on-kubernetes.md
Signed-off-by: “fewdan” <fewdan@hotmail.com>
fix issue https://github.com/chaos-mesh/chaos-mesh/issues/2287.
> update networkchaos dos and fix typo

- blog/2020-07-28-chaos-mesh-join-cncf-sandbox-project.md
- blog/2020-08-14-building_automated_testing_framework.md
- blog/2020-9-25-chaos-mesh-1.0-chaos-engineering-on-kubernetes-made-easier.md
- blog/2021-06-25-chaos-mesh-remake-one-step-closer-toward-chaos-as-a-service.md
- blog/2021-07-07-restrict-authorization.md
- blog/2021-07-09-chaos-mesh-q&a.md
- blog/2021-08-05-chaos-mesh-celebrates-100-contributors.md
- blog/2021-08-20-chaos-mesh-apisix.md
- blog/2021-09-15-run-chaos-experiments-on-physical-machines.md
- docusaurus.config.js
- i18n/zh/docusaurus-theme-classic/footer.json
- i18n/zh/docusaurus-theme-classic/navbar.json
- src/pages/index.js
Signed-off-by: Mila Wu <wumila1996@gmail.com>
This is to remove the registered trademark symbol ® on the Chaos Mesh website, as Chaos Mesh will no longer be carrying this symbol.
> chores: remove registered trademark symbol

- docs/common/verify-installation.md
- docs/production-installation-using-helm.md
- i18n/zh/docusaurus-plugin-content-docs/current/common/verify-installation.md
- i18n/zh/docusaurus-plugin-content-docs/current/production-installation-using-helm.md
Signed-off-by: SiyuChen <ryougi201@gmail.com>
close https://github.com/chaos-mesh/website/issues/139
> chore: add notes about leader-election

- docs/offline-installation.md
- i18n/zh/docusaurus-plugin-content-docs/current/offline-installation.md
Update image name used by offline installation.
> update images for offline installation

- docs/simulate-network-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-network-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.0.5/simulate-network-chaos-on-kubernetes.md
- versioned_docs/version-2.0.5/simulate-network-chaos-on-kubernetes.md
Appending description about field `externalTargets` in Network Chaos
> docs: descriptions about externalTarget in NetworkChaos

- docs/simulate-time-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-time-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.0.5/simulate-time-chaos-on-kubernetes.md
- versioned_docs/version-2.0.5/simulate-time-chaos-on-kubernetes.md
Update the notes about the scope of timechaos
> chore: update note for time chaos

- i18n/zh/docusaurus-plugin-content-docs/current/simulate-physical-machine-chaos.md
> document: add the version mapping between Chaosd and Chaos Mesh

- docs/offline-installation.md
- i18n/zh/docusaurus-plugin-content-docs/current/offline-installation.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.0/offline-installation.md
- versioned_docs/version-2.1.0/offline-installation.md
> update offline installation

- docs/offline-installation.md
- i18n/zh/docusaurus-plugin-content-docs/current/offline-installation.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.0.5/offline-installation.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.0/offline-installation.md
- src/components/PickVersion.jsx
- versioned_docs/version-2.0.5/offline-installation.md
- versioned_docs/version-2.1.0/offline-installation.md
Ref: https://github.com/chaos-mesh/website/pull/182#issuecomment-985190415.
This PR aims to render different archive download links depending on the version.
> chore: replace version to branch name

- docs/production-installation-using-helm.md
- i18n/zh/docusaurus-plugin-content-docs/current/production-installation-using-helm.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.0.5/production-installation-using-helm.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.0/production-installation-using-helm.md
- versioned_docs/version-2.0.5/production-installation-using-helm.md
- versioned_docs/version-2.1.0/production-installation-using-helm.md
Update the CRI-O configuration with helm
> docs: add description about crio config in helm

- docs/add-new-chaos-experiment-type.md
- i18n/zh/docusaurus-plugin-content-docs/current/add-new-chaos-experiment-type.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.0.5/add-new-chaos-experiment-type.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.0/add-new-chaos-experiment-type.md
- versioned_docs/version-2.0.5/add-new-chaos-experiment-type.md
- versioned_docs/version-2.1.0/add-new-chaos-experiment-type.md
The code generation part of the tutorial is incorrect because of https://github.com/chaos-mesh/chaos-mesh/pull/2353
> docs: fix helloworldchaos tutorial

- i18n/zh/docusaurus-plugin-content-docs/current/production-installation-using-helm.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.0.5/production-installation-using-helm.md
- versioned_docs/version-2.0.5/production-installation-using-helm.md
- versioned_docs/version-2.1.0/production-installation-using-helm.md
> docs: use replace to upgrade CRDs

- i18n/zh/docusaurus-plugin-content-docs/current/simulate-http-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.0.5/simulate-http-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.0/simulate-http-chaos-on-kubernetes.md
Signed-off-by: xixi <i@hexilee.me>
> fix(httpchaos): example value of patch body

- docs/uninstallation.md
- i18n/zh/docusaurus-plugin-content-docs/current/uninstallation.md
- sidebars.js
> New Docs: Uninstallation

- docs/create-chaos-mesh-workflow.md
- i18n/zh/docusaurus-plugin-content-docs/current/create-chaos-mesh-workflow.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.0.5/create-chaos-mesh-workflow.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.1/create-chaos-mesh-workflow.md
- versioned_docs/version-2.0.5/create-chaos-mesh-workflow.md
- versioned_docs/version-2.1.1/create-chaos-mesh-workflow.md
This PR update several bad URLs which break the CI markdown linters
> chore: update urls

- i18n/zh/docusaurus-plugin-content-docs/version-2.1.1/uninstallation.md
- versioned_docs/version-2.1.1/uninstallation.md
- versioned_sidebars/version-2.1.1-sidebars.json
> chore: update uninstallation on 2.1.1

- blog/2021-12-27-chaos-mesh-story.md
- To remove unnecessary title section
- To add link on the hashtag
Signed-off-by: Mila Wu <wumila1996@gmail.com>
> chores: edit chaos mesh 2yr-event blog

- docs/chaosd-search-recover.md
- i18n/zh/docusaurus-plugin-content-docs/current/chaosd-search-recover.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.1/chaosd-search-recover.md
- versioned_docs/version-2.1.1/chaosd-search-recover.md
Signed-off-by: en-jin19 <jinenwei@pingcap.com>
Translated from:
- https://github.com/chaos-mesh/website/pull/161
- https://github.com/chaos-mesh/website/pull/174
> docs: Search and Recover Experiments of Chaosd

- versioned_docs/version-0.9.1/user_guides/timechaos.md
- versioned_docs/version-1.0.3/chaos_experiments/timechaos.md
- versioned_docs/version-1.1.4/chaos_experiments/timechaos.md
- versioned_docs/version-1.2.4/chaos_experiments/timechaos.md
> fix container selector documents

- docs/simulate-network-chaos-in-physical-nodes.md
- docs/simulate-time-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-heavy-stress-in-physical-nodes.md
- versioned_docs/version-2.0.6/simulate-time-chaos-on-kubernetes.md
- versioned_docs/version-2.1.2/simulate-time-chaos-on-kubernetes.md
> chore: format note

- docs/simulate-gcp-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-gcp-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.0.6/simulate-gcp-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.2/simulate-gcp-chaos.md
- versioned_docs/version-2.0.6/simulate-gcp-chaos.md
- versioned_docs/version-2.1.2/simulate-gcp-chaos.md
> docs: add docs link for gcp sercvice account key

- versioned_docs/version-2.0.6/overview.md
- versioned_docs/version-2.1.2/overview.md
To update the versioned docs as per this PR: #233.
Signed-off-by: Mila Wu <wu.zaixuan@hotmail.com>
> chores: update project info in versioned docs

- docs/add-new-chaos-experiment-type.md
- i18n/zh/docusaurus-plugin-content-docs/current/add-new-chaos-experiment-type.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.0.6/add-new-chaos-experiment-type.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.2/add-new-chaos-experiment-type.md
- versioned_docs/version-2.0.6/add-new-chaos-experiment-type.md
- versioned_docs/version-2.1.2/add-new-chaos-experiment-type.md
Signed-off-by: “fewdan” <fewdan@hotmail.com>
update docs of add a new type chaos
replace "pingcap" by "chaos-mesh"
> chore: update docs of add a new type chaos

- src/pages/index.js
- versioned_docs/version-2.0.7/overview.md
- versioned_docs/version-2.1.3/overview.md
To complete what #241 started ;)
Signed-off-by: Mila Wu [wumila1996@gmail.com](mailto:wumila1996@gmail.com)
This PR is translated from https://github.com/chaos-mesh/website/pull/250
> chores: update chaos mesh project status

- docs/configure-development-environment.md
- i18n/zh/docusaurus-plugin-content-docs/current/configure-development-environment.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.3/configure-development-environment.md
- versioned_docs/version-2.1.3/configure-development-environment.md
> fix: update start:default commands

- docs/simulate-process-chaos-in-physical-nodes.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-process-chaos-in-physical-nodes.md
Signed-off-by: FingerLeader <wanxfinger@gmail.com>
> add doc for recover-cmd

- docs/developer-guide-overview.md
- i18n/zh/docusaurus-plugin-content-docs/current/developer-guide-overview.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.3/developer-guide-overview.md
- versioned_docs/version-2.1.3/developer-guide-overview.md
Signed-off-by: Cwen Yin <cwenyin0@gmail.com> 
Close: #259
> Docs: add coding guidelines

- versioned_docs/version-0.9.1/user_guides/iochaos.md
> document: fix link

- docs/simulate-heavy-stress-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-heavy-stress-on-kubernetes.md
Fix https://github.com/chaos-mesh/chaos-mesh/issues/3069
Add document for the newly added `oomScoreAdj` field
> add document for stress oom_score_adj

- docs/simulate-heavy-stress-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-heavy-stress-on-kubernetes.md
Signed-off-by: FingerLeader <wanxfinger@gmail.com>
> Update the description of MemoryStrossors size in simulate-heavy-stress-on-kubernetes.md

- blog/2021-06-25-chaos-mesh-remake-one-step-closer-toward-chaos-as-a-service.md
- docs/simulate-physical-machine-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-network-chaos-in-physical-nodes.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-physical-machine-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-network-chaos-in-physical-nodes.md
minor fix on document by the way
> update the version map between Chaosd and Chaos Mesh

- docs/uninstallation.md
Update validate-auth to chaos-mesh-validate-auth
Refer: https://github.com/chaos-mesh/chaos-mesh/pull/3193
> Update validate-auth to chaos-mesh-validate-auth

- docs/simulate-process-chaos-in-physical-nodes.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-process-chaos-in-physical-nodes.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-process-chaos-in-physical-nodes.md
- versioned_docs/version-2.1.5/simulate-process-chaos-in-physical-nodes.md
Signed-off-by: vampireqian <vampire.luo@foxmail.com>
> chaosd: add a doc to introduce how to pause the program on service mode

- docs/simulate-pod-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-pod-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/simulate-pod-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-pod-chaos-on-kubernetes.md
- versioned_docs/version-2.0.7/simulate-pod-chaos-on-kubernetes.md
- versioned_docs/version-2.1.5/simulate-pod-chaos-on-kubernetes.md
Signed-off-by: STRRL <im@strrl.dev>
close https://github.com/chaos-mesh/website/issues/231
> docs: update usage restriction for podchaos

- docs/simulate-file-chaos-in-physical-nodes.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-file-chaos-in-physical-nodes.md
- sidebars.js
close #249 
TODO: translate to English
> document: simulate file fault in physical machine by using chaosd

- docs/simulate-network-chaos-in-physical-nodes.md
> Update the English document of simulating network fault into physical machine by using chaosd

- docs/simulate-http-chaos-on-kubernetes.md
Signed-off-by: xixi <i@hexilee.me>
Complete #261, please review the [rendered document](https://github.com/Hexilee/website/blob/update-http-chaos/docs/simulate-http-chaos-on-kubernetes.md#specify-side).
> indicate the changes of HTTPChaos behaviors

- docs/simulate-aws-chaos.md
- docs/simulate-azure-chaos.md
- docs/simulate-gcp-chaos.md
- docs/simulate-jvm-application-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-aws-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-azure-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-dns-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-gcp-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-kernel-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-physical-machine-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/simulate-aws-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/simulate-dns-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/simulate-gcp-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/simulate-kernel-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-aws-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-dns-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-gcp-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-kernel-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/simulate-physical-machine-chaos.md
- sidebars.js
- versioned_docs/version-1.2.4/chaos_experiments/awschaos.md
- versioned_docs/version-2.0.7/simulate-aws-chaos.md
- versioned_docs/version-2.0.7/simulate-gcp-chaos.md
- versioned_docs/version-2.1.5/simulate-aws-chaos.md
- versioned_docs/version-2.1.5/simulate-gcp-chaos.md
- versioned_docs/version-2.1.5/simulate-jvm-application-chaos.md
Signed-off-by: FingerLeader <wanxfinger@gmail.com>
> Add docs of AzureChaos

- docs/upgrade-from-2.1-to-2.2.md
- i18n/zh/docusaurus-plugin-content-docs/current/upgrade-from-2.1-to-2.2.md
- sidebars.js
Signed-off-by: STRRL <im@strrl.dev>
close https://github.com/chaos-mesh/website/issues/281
> docs: upgrade from 2.1 to 2.2

- blog/2022-06-07-chaos-mesh-qa-kubecon-eu-2022.md
Signed-off-by: luzizhuo <496521310@qq.com>
> Blog:Chaos Mesh Q&A at KUBECON EU 2022

- i18n/zh/docusaurus-plugin-content-docs/current/simulate-network-chaos-in-physical-nodes.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/simulate-network-chaos-in-physical-nodes.md
> zh document: update dns example for chaosd

- docs/configure-development-environment.md
Close https://github.com/chaos-mesh/website/issues/310
> configure the develop environment

- docs/upgrade-from-2.1-to-2.2.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/upgrade-from-2.1-to-2.2.md
- versioned_docs/version-2.2.0/upgrade-from-2.1-to-2.2.md
Signed-off-by: Aolin <aolin.zhang@pingcap.com>
> Fix the note format in upgrade-from-2.1-to-2.2.md

- docs/simulate-http-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-http-chaos-on-kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/simulate-http-chaos-on-kubernetes.md
- versioned_docs/version-2.2.0/simulate-http-chaos-on-kubernetes.md
Signed-off-by: Xianglin Gao <xianglingao@tencent.com>
> Clarify the usage of replace.body

- blog/2022-06-07-chaos-mesh-qa-kubecon-eu-2022.md
Signed-off-by: Mila Wu <wumila1996@gmail.com>
> chore: add truncate for blog

- docs/chaosctl-tool.md
- i18n/zh/docusaurus-plugin-content-docs/current/chaosctl-tool.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.3.0/chaosctl-tool.md
- versioned_docs/version-2.3.0/chaosctl-tool.md
Signed-off-by: Aolin <aolin.zhang@pingcap.com>
Close https://github.com/chaos-mesh/website/issues/327
> add --remote-name flag when downloading chaosctl

- docs/production-installation-using-helm.md
Signed-off-by: Trevor Sullivan <trevor@trevorsullivan.net>
> Clarify purpose of safe mode

- docs/define-scheduling-rules.md
- i18n/zh/docusaurus-plugin-content-docs/current/define-scheduling-rules.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.3.0/define-scheduling-rules.md
- versioned_docs/version-2.3.0/define-scheduling-rules.md
Signed-off-by: Aolin <aolin.zhang@pingcap.com>
Close https://github.com/chaos-mesh/website/issues/336
> the default value of startingDeadlineSeconds is not 0, is nil

- docs/define-chaos-experiment-scope.md
- docs/simulate-physical-machine-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/current/simulate-physical-machine-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.2.3/simulate-physical-machine-chaos.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.3.0/simulate-physical-machine-chaos.md
- versioned_docs/version-2.2.3/define-chaos-experiment-scope.md
- versioned_docs/version-2.2.3/simulate-physical-machine-chaos.md
- versioned_docs/version-2.3.0/define-chaos-experiment-scope.md
- versioned_docs/version-2.3.0/simulate-physical-machine-chaos.md
Fix chaosd startup parameter error
> Fix misspelling of chaosd

- docs/configure-enabled-namespace.md
- versioned_docs/version-2.0.7/configure-enabled-namespace.md
- versioned_docs/version-2.1.7/configure-enabled-namespace.md
- versioned_docs/version-2.2.3/configure-enabled-namespace.md
- versioned_docs/version-2.3.0/configure-enabled-namespace.md
Signed-off-by: brnck <a.berneckas@gmail.com>
> Fix docs mistypes in configure-enabled-namespace section

- blog/2020-01-15-chaos-mesh-your-chaos-engineering-solution.md
- blog/2020-04-20-simulating-clock-skew-in-k8s-without-affecting-other-containers-on-node.md
- blog/2021-06-25-chaos-mesh-remake-one-step-closer-toward-chaos-as-a-service.md
Signed-off-by: Aolin <aolin.zhang@pingcap.com>
> fix broken links

- docs/remote-cluster-management.md
> add document for remote cluster management

- sidebars.js
- versioned_docs/version-2.5.0/remote-cluster-management.md
- versioned_sidebars/version-2.5.0-sidebars.json
> v2.5: add remote-cluster-management doc

- docs/production-installation-using-helm.md
- i18n/zh/docusaurus-plugin-content-docs/current/production-installation-using-helm.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.2.3/production-installation-using-helm.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.3.3/production-installation-using-helm.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/production-installation-using-helm.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.5.0/production-installation-using-helm.md
- versioned_docs/version-2.2.3/production-installation-using-helm.md
- versioned_docs/version-2.3.3/production-installation-using-helm.md
- versioned_docs/version-2.4.3/production-installation-using-helm.md
- versioned_docs/version-2.5.0/production-installation-using-helm.md
Signed-off-by: cwen0 <cwenyin0@gmail.com> 
close: https://github.com/chaos-mesh/chaos-mesh/issues/3829
> update leaderElection doc

- docs/simulate-block-chaos-on-kubernetes.md
> docs: add document about blockchaos freeze action

- i18n/zh/docusaurus-plugin-content-docs/current/check-workflow-status.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.3.3/check-workflow-status.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/check-workflow-status.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.5.1/check-workflow-status.md
> chore: replace "Workflow" to "工作流" in check-workflow-status.md

- docs/define-scheduling-rules.md
- i18n/zh/docusaurus-plugin-content-docs/current/define-scheduling-rules.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.3.3/define-scheduling-rules.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/define-scheduling-rules.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.5.1/define-scheduling-rules.md
- versioned_docs/version-2.3.3/define-scheduling-rules.md
- versioned_docs/version-2.4.3/define-scheduling-rules.md
- versioned_docs/version-2.5.1/define-scheduling-rules.md
Refer to https://github.com/chaos-mesh/chaos-mesh/discussions/3881, this pr adds more details about the `schedule` field.
> chore: more details about schedule

- i18n/zh/docusaurus-plugin-content-docs/current/basic-features.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.3.3/basic-features.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/basic-features.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.5.1/basic-features.md
> chore: replace "Workflow" to "工作流" in basic-features.md

- docs/simulate-dns-chaos-on-kubernetes.md
> chore: deploy dns server by default

- docs/simulate-aws-chaos.md
Updating docs related to https://github.com/chaos-mesh/chaos-mesh/pull/4066
Also relates to https://github.com/chaos-mesh/chaos-mesh/issues/4065
> updating docs for https://github.com/chaos-mesh/chaos-mesh/pull/4066

- docs/production-installation-using-helm.md
- i18n/zh/docusaurus-plugin-content-docs/current/production-installation-using-helm.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/production-installation-using-helm.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.5.2/production-installation-using-helm.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.6.2/production-installation-using-helm.md
- versioned_docs/version-2.4.3/production-installation-using-helm.md
- versioned_docs/version-2.5.2/production-installation-using-helm.md
- versioned_docs/version-2.6.2/production-installation-using-helm.md
> chore: Installation in microk8s

- docs/simulate-dns-chaos-on-kubernetes.md
- versioned_docs/version-2.6.2/simulate-dns-chaos-on-kubernetes.md
* Fix <PickHelmVersion> function usage
> Fix doc crash

- docs/configure-development-environment.md
- versioned_docs/version-2.4.3/configure-development-environment.md
- versioned_docs/version-2.5.2/configure-development-environment.md
- versioned_docs/version-2.6.2/configure-development-environment.md
reference: `DEBUGGER=1` on [chaos-mesh Makefile](https://github.com/chaos-mesh/chaos-mesh/blob/master/Makefile#L10).
> Update debug make image flag.

- docs/gcp-authentication.md
- i18n/zh/docusaurus-plugin-content-docs/current/gcp-authentication.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/gcp-authentication.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.5.2/gcp-authentication.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.6.2/gcp-authentication.md
- versioned_docs/version-2.4.3/gcp-authentication.md
- versioned_docs/version-2.5.2/gcp-authentication.md
- versioned_docs/version-2.6.2/gcp-authentication.md
Update docs for https://github.com/chaos-mesh/chaos-mesh/pull/4303.
> docs: gcp security with secret

- package.json
- pnpm-lock.yaml
- src/components/Card.jsx
- src/pages/index.module.css
- tailwind.config.js
See https://daisyui.com/docs/changelog/#400-2023-11-12. The main change in daisyui v4 is adopting [OKLCH colors](https://oklch.com/).
> feat: upgrade daisyui to v4

- docusaurus.config.js
- package.json
- pnpm-lock.yaml
Microsoft Clarity is a new user analytics tools, it could provide more awesome features like session replay and heatmap.
> feat: setup microsoft clarity

- static/.well-known/funding-manifest-urls
like https://github.com/chaos-mesh/chaos-mesh/pull/4529
This PR makes endorsements for our maintainers @STRRL and @g1eny0ung for their contribution, supports them accept funding as individuals.
> chore: support endorsement for our maintainers

- README.md
Refer to #420 and #421, I updated the README for related changes.
> docs: how to add a new language translation

- docs/common/_verify-installation.md
- i18n/zh/docusaurus-plugin-content-docs/current/common/_verify-installation.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.5.2/common/_verify-installation.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.6.6/common/_verify-installation.md
- i18n/zh/docusaurus-plugin-content-docs/version-2.7.1/common/_verify-installation.md
- versioned_docs/version-2.5.2/common/_verify-installation.md
- versioned_docs/version-2.6.6/common/_verify-installation.md
- versioned_docs/version-2.7.1/common/_verify-installation.md
> fix: pods output when leader election enabled
