docs/get_started/run_chaos_experiment.md
versioned_docs/version-0.9.1/user_guides/run_chaos_experiment.md
versioned_docs/version-1.0.0/user_guides/run_chaos_experiment.md
versioned_docs/version-1.0.1/get_started/run_chaos_experiment.md

If you install the helm chart with 
`helm install chaos-mesh chaos-mesh/chaos-mesh --namespace=chaos-testing`
then the same chart name should be used for the upgrade

Keep the chart name consistent with the previous'

---

docs/chaos_experiments/io_chaos.md
versioned_docs/version-1.0.2/chaos_experiments/io_chaos.md

Signed-off-by: yiyiyimu <wosoyoung@gmail.com>
Ref:
https://github.com/chaos-mesh/chaos-mesh/blob/8581cd063bc18b57d7135915401346b45eecef90/api/v1alpha1/podiochaos_types.go#L61-L73
```
// IoChaosType represents the type of an IoChaos Action
type IoChaosType string
const (
// IoLatency represents injecting latency for io operation
IoLatency IoChaosType = "latency"
// IoFaults represents injecting faults for io operation
IoFaults IoChaosType = "fault"
// IoAttrOverride represents replacing attribution for io operation
IoAttrOverride IoChaosType = "attrOverride"
)
```

fix io chaos action

---

.github/workflows/checklink.yaml
.github/workflows/checklink_config.json
blog/2020-9-25-chaos-mesh-1.0-chaos-engineering-on-kubernetes-made-easier.md

Signed-off-by: yiyiyimu <wosoyoung@gmail.com>
The aim of adding a link checker to chaos-mesh/chaos-mesh is to check the dead links on the website. Since the website is moved to this repo, it would be better also move the link checker here.

add link checker from chaos-mesh repo

---

docs/user_guides/installation.md

https://github.com/chaos-mesh/chaos-mesh/pull/1236 , we need to bypass the validation of kubernetes to add a field `preserveUnknownFields` on lower versions of kubernetes.
Signed-off-by: Yang Keao <keao.yang@yahoo.com>

docs: bypass validation for lower version of kubernetes

---

docs/get_started/get_started_on_minikube.md
versioned_docs/version-1.0.2/get_started/get_started_on_minikube.md

Signed-off-by: yiyiyimu <wosoyoung@gmail.com>
Following the official installation step on [release installation suggestion](https://github.com/helm/helm/releases/tag/v3.4.1) and [doc installation steps](https://helm.sh/docs/intro/install/#from-script), update helm installation from v2 to v3.

chore: update minikube installation to helm v3

---

blog/2021-01-08-how-to-simulate-io-faults-at-runtime.md

"How to XXX" is not a question, so we must remove the question mark. We already deleted "?" in the blog post on the PingCAP website.

Remove "?"

---

docs/chaos_experiments/stress_chaos.md
versioned_docs/version-1.0.3/chaos_experiments/stress_chaos.md
versioned_docs/version-1.1.0/chaos_experiments/stress_chaos.md

Signed-off-by: Yang Keao <keao.yang@yahoo.com>
The size parameter of a memory stress chaos has been removed several months ago.

remove size parameter of stress chaos

---

docs/chaos_experiments/dns_chaos.md

https://github.com/chaos-mesh/chaos-mesh/pull/1454 this pr remove the field `scope` and add a new field `pattern`, so need to update the document.

docs: add new field `patterns` for DNS chaos

---

versioned_docs/version-1.2.1/faqs.md

Message most looked like this:
```bash
Error creating: pods "chaos-dns-server-123aa56123-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.capabilities.add: Invalid value: "NET_BIND_SERVICE": capability may not be added]
```
You need to add privileged scc to default.
```bash
oc adm policy add-scc-to-user privileged -n chaos-testing -z chaos-dns-server
```

DNSChaos on OpenShift permissions issue resolution

---

docs/simulate-http-chaos-on-kubernetes.md

I currently see the page with:

Replace broken character with colon character

---

blog/2020-01-15-chaos-mesh-your-chaos-engineering-solution.md
docs/configure-enabled-namespace.md
docs/simulate-heavy-stress-in-physical-nodes.md
docs/simulate-heavy-stress-on-kubernetes.md
docs/simulate-http-chaos-on-kubernetes.md
docs/simulate-io-chaos-on-kubernetes.md
docs/simulate-jvm-application-chaos.md
docs/simulate-network-chaos-in-physical-nodes.md
docs/simulate-network-chaos-on-kubernetes.md
docs/simulate-pod-chaos-on-kubernetes.md
docs/simulate-process-chaos-in-physical-nodes.md
versioned_docs/version-2.0.0/configure-enabled-namespace.md
versioned_docs/version-2.0.0/simulate-disk-pressure-in-physical-nodes.md
versioned_docs/version-2.0.0/simulate-heavy-stress-in-physical-nodes.md
versioned_docs/version-2.0.0/simulate-heavy-stress-on-kubernetes.md
versioned_docs/version-2.0.0/simulate-http-chaos-on-kubernetes.md
versioned_docs/version-2.0.0/simulate-io-chaos-on-kubernetes.md
versioned_docs/version-2.0.0/simulate-network-chaos-in-physical-nodes.md
versioned_docs/version-2.0.0/simulate-network-chaos-on-kubernetes.md
versioned_docs/version-2.0.0/simulate-pod-chaos-on-kubernetes.md
versioned_docs/version-2.0.0/simulate-process-chaos-in-physical-nodes.md

* Updated documentation and blog post with correct terminology (daemonset -> DaemonSet, etc)
* Fixed some set of tpyos (Descpription -> Description, etc)
* Fix typos in k8s object specification (labelselectors -> labelSelectors)
* Replaced Chinese character ： for latin :
* Made more consistent formatting around types of actions:
* if action is a technical keyword like latency it's formatted as `latency`, if fault type is a general terminology it's formatted in bold **Pod Failure**
* Fixed a few broken links - link in md need to be in lower case, having `YAML` in a link doesn't create HTML anchor, it needs to be `yaml`
I made two commits with the same changes, one commit affects versioned documentation for 2.0.0 and another commit is general for non-versioned docs, for something I assume …

Fix documentation typos, broken links and formatting

---

docs/basic-features.md

It seems scenario is not really used anywhere apart from this feature list. I assume that this is an old name for the workflow engine introduced in v2 and reworded a few bits in the paragraph mentioning workflows.

fix: mention of scenario

---

docs/offline-installation.md
i18n/zh/docusaurus-plugin-content-docs/current/offline-installation.md
i18n/zh/docusaurus-plugin-content-docs/version-2.0.4/offline-installation.md
versioned_docs/version-2.0.4/offline-installation.md

Signed-off-by: Eric Shen <ericshenyuhao@outlook.com>
The command of `curl https://github.com/chaos-mesh/chaos-mesh/archive/refs/heads/master.zip -o chaos-mesh.zip` will get a zip file which cannot be unziped. 
The correct command should be `curl -fsSL -o chaos-mesh.zip https://github.com/chaos-mesh/chaos-mesh/archive/refs/heads/master.zip`.

fix(docs): incorrect command to download charts

---

src/components/PickHelmVersion.jsx

Signed-off-by: cwen0 <cwenyin0@gmail.com> 
Fix JS float pitfall. This issue will cause that helm version to show a wrong value, like:  
Fixed: 
**PS: This pr is not the best solution for JS float pitfall, but it works well here.**

fix: JS float pitfall

---

versioned_docs/version-2.1.3/production-installation-using-helm.md

I believe i found a typo in the documentation when i was working on my own project
Let me know if i'm wrong - i will delete the PR

Typo in helm chart repo link fix

---

i18n/zh/docusaurus-plugin-content-docs/current/simulate-jvm-application-chaos-in-physical-nodes.md

document: inject fault into MySQL java client by chaosd

---

blog/2021-06-25-chaos-mesh-remake-one-step-closer-toward-chaos-as-a-service.md

Signed-off-by: Aolin Zhang <aolin.zhang@pingcap.com>
Close: https://github.com/chaos-mesh/website/issues/290
Remove WASM link because [wasm transform to be removed from Vector](https://vector.dev/highlights/2021-08-23-removing-wasm/)

Remove Vector WASM Transform link

---

docs/offline-installation.md
i18n/zh/docusaurus-plugin-content-docs/current/offline-installation.md
i18n/zh/docusaurus-plugin-content-docs/version-2.0.7/offline-installation.md
i18n/zh/docusaurus-plugin-content-docs/version-2.1.5/offline-installation.md
src/components/PickVersion.jsx
versioned_docs/version-2.0.7/offline-installation.md
versioned_docs/version-2.1.5/offline-installation.md

Signed-off-by: STRRL <im@strrl.dev>
It's a part of https://github.com/chaos-mesh/website/issues/301

fix the usage of PickVersion in offline installation

---

versioned_docs/version-2.2.0/simulate-io-chaos-on-kubernetes.md

General fields ContainerName should be containerNames, and type is  []string

fix: correct IOChaos containerNames

---

i18n/zh/docusaurus-plugin-content-docs/current/simulate-jvm-application-chaos-in-physical-nodes.md
i18n/zh/docusaurus-plugin-content-docs/current/simulate-jvm-application-chaos.md
i18n/zh/docusaurus-plugin-content-docs/version-2.2.0/simulate-jvm-application-chaos-in-physical-nodes.md

fix issue https://github.com/chaos-mesh/website/issues/245

document: add description for injecting JVM fault into MySQL client

---

docs/common/verify-installation.md
i18n/zh/docusaurus-plugin-content-docs/current/common/verify-installation.md
i18n/zh/docusaurus-plugin-content-docs/version-2.3.1/common/verify-installation.md
versioned_docs/version-2.3.1/common/verify-installation.md

- Problem: namespace `chaos-testing` shown in "Quick Start" page does not exist in the specified version (`v2.3.1`) of Chaos Mesh
- Fix by this PR: the namespace is updated to `chaos-mesh`, the correct one
---
Signed-off-by: Akira Hayashi <smxshxishxad@me.com>

Correct namespace in Quick Start

---

docs/supported-releases.md

Update documentation on supported k8s versions
Version are based on https://github.com/chaos-mesh/chaos-mesh/pull/3630
This PR is part of the 2.4.0 release:
https://github.com/chaos-mesh/chaos-mesh/blob/release-2.4/.github/workflows/e2e_test.yml#L107
Given that the lowest version tested is 1.20 - removing everything below it from the supported list and adding releases up to 1.25 instead

Update supported k8s versions

---

versioned_docs/version-2.5.0/simulate-network-chaos-on-kubernetes.md

Bandwidth limit string -> int.
Output from kubectl apply:
kubectl apply -f bandwidth.yaml
error: error validating "bandwidth.yaml": error validating data: ValidationError(NetworkChaos.spec.bandwidth.limit): invalid type for org.chaos-mesh.v1alpha1.NetworkChaos.spec.bandwidth.limit: got "string", expected "integer"; if you choose to ignore these errors, turn validation off with --validate=false

Correct parameter type for Bandwidth limit

---

docs/manage-user-permissions.md
versioned_docs/version-2.3.3/manage-user-permissions.md
versioned_docs/version-2.4.3/manage-user-permissions.md
versioned_docs/version-2.5.1/manage-user-permissions.md

Refer to https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account:
> Versions of Kubernetes before v1.22 automatically created long term credentials for accessing the Kubernetes API. This older mechanism was based on creating token Secrets that could then be mounted into running Pods. In more recent versions, including Kubernetes v1.26, API credentials are obtained directly by using the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API, and are mounted into Pods using a [projected volume](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume). The tokens obtained using this method have bounded …

chore: manually create an API token for a ServiceAccount

---

versioned_docs/version-2.5.1/define-scheduling-rules.md

Change the title to match the actual field name to match the other examples on this page.
For me, the title is confusing and not clear in what the field matches and can/could cause confusion to others.

Fix `concurrencyPolicy` title in define-scheduling-rules.md

---

docs/simulate-io-chaos-on-kubernetes.md

Fixed typos in the IOChaos mistake example

fix typos in iochaos example

---

docs/simulate-azure-chaos.md

Its missing in the documentation but a required property to run the experiment.

docs: add VMName property to AzureChaos documentation

---

docs/simulate-network-chaos-on-kubernetes.md

Ref: https://github.com/chaos-mesh/chaos-mesh/pull/4129

docs: support more rate units for networkchaos/bandwidth

---

docs/simulate-http-chaos-on-kubernetes.md
versioned_docs/version-2.4.3/simulate-http-chaos-on-kubernetes.md
versioned_docs/version-2.5.2/simulate-http-chaos-on-kubernetes.md
versioned_docs/version-2.6.2/simulate-http-chaos-on-kubernetes.md

fix typo, `Simulate HTTP faults` -> `Simulate HTTP Faults`

fix: title of Simulate HTTP faults

---

docs/remote-cluster-management.md
i18n/zh/docusaurus-plugin-content-docs/current/remote-cluster-management.md

Update:
Chinese documentation for `Remote Cluster Management`.
Fix:
The meaning of `kubeConfig.secretRef.namespace` in the English document of `Remote Cluster Management`.

fix: `kubeConfig.secretRef.namespace` description and provide zh doc of Remote Cluster

---

docs/simulate-network-chaos-on-kubernetes.md
i18n/zh/docusaurus-plugin-content-docs/current/simulate-network-chaos-on-kubernetes.md
i18n/zh/docusaurus-plugin-content-docs/version-2.4.3/simulate-network-chaos-on-kubernetes.md
i18n/zh/docusaurus-plugin-content-docs/version-2.5.2/simulate-network-chaos-on-kubernetes.md
i18n/zh/docusaurus-plugin-content-docs/version-2.6.2/simulate-network-chaos-on-kubernetes.md
versioned_docs/version-2.4.3/simulate-network-chaos-on-kubernetes.md
versioned_docs/version-2.5.2/simulate-network-chaos-on-kubernetes.md
versioned_docs/version-2.6.2/simulate-network-chaos-on-kubernetes.md

This PR updates the documentation for the `rate` action added to network chaos. 
https://github.com/chaos-mesh/chaos-mesh/pull/4017

[docs] add rate simulatation to network chaos

---

src/pages/supported-releases.md

Follows https://github.com/chaos-mesh/chaos-mesh/pull/4319, updates the supported k8s versions.

chore: update supported k8s versions
